### PR TITLE
Better icons (font-awesome) and navigation improvements

### PR DESCRIPTION
**Pull request by brodock**
icons
back-to-top
plugin type list

### CODE REVIEW

**Comment by brodock** [comment]
@jimmycuadra I've tried some minimal polishments here... I want to do some additional work on the plugin list (use 2 or 3 columns to list them depending on the windows size, to make a better use of vertical space). Also some repeated labels are a good candidate to be replaced by an icon (like "Required lita version")

**Comment by jimmycuadra** [comment]
Looks really nice! I'm not clear on why the custom bootstrap SCSS file is necessary, though. Could you explain what it's doing that importing bootstrap directly doesn't do? Why is it no longer necessary to import bootstrap-sprockets?

**Comment by brodock** [comment]
@jimmycuadra sure, we need to customize the import to replace glyphicons with Font Awesome (so we don't load something we don't use).

**Comment by jimmycuadra** [comment]
Sorry for the delay! Thanks for this!

**Pull request merged**
